language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=healthcheck
  # - TOXENV=sphinx # broken link: https://pythonhosted.org/twod.wsgi/embedded-apps.html
  - TOXENV=readme
install:
  - pip install -U pip setuptools
  - pip install tox
script:
  - tox
